import { ConnectKitButton } from "connectkit";
import { type NextPage } from "next";
import Head from "next/head";
import { ContractViewFunctions } from "../components/contractViewFn";
import { ContractWriteFunctions } from "../components/contractWriteFn";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Reignover</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          <p className="text-white font-thin">Add some really cool text here to see what it will look like. Zebras are amazing.</p>
          <ConnectKitButton />
          <div className="flex flex-row justify-between">
            <ContractWriteFunctions />
            <ContractViewFunctions />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
