import { ConnectKitButton } from "connectkit";
import { type NextPage } from "next";
import Head from "next/head";
import { ContractViewFunctions } from "../components/contractViewFnAll";
import { ContractWriteFunctions } from "../components/contractWriteFnAll";
import { resourcesABI } from "../utils/abis/Resources";
import { VolumeNFTAddress } from "../utils/constants";
import { AbiItem } from "../utils/types/abi";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Reignover</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
          </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          <ConnectKitButton />
          <div className="flex flex-row justify-between">
            <ContractWriteFunctions ABI={resourcesABI as AbiItem[]} contractAddress={VolumeNFTAddress} />
            <ContractViewFunctions ABI={resourcesABI as AbiItem[]} contractAddress={VolumeNFTAddress} />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
